name: Build
on:
  push:
    branches: [main]
  release:
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'chore(registry): update registry')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: install go
        run: |
          curl -OL https://go.dev/dl/go1.22.1.linux-amd64.tar.gz
          rm -rf /usr/local/go 
          sudo tar -C /usr/local -xzf go1.22.1.linux-amd64.tar.gz
      - name: Build
        run: |
          go run main.go > registry.json
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(registry): update registry"
          file_pattern: "./registry.json"
          push_options: "--force"
